version: "3.9"

services:
  frontend:
    build:
      context: ./finance-wise  
    container_name: frontend
    ports:
      - "80:80"  
    depends_on:
      - backend  
    networks:
      - app-network

  backend:
    build:
      context: ./finance-wise-api
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=mysecretpassword
      - DATABASE_NAME=mydb
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:13 
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
