services:
  database:
    image: postgres:latest
    container_name: postgres-container  
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
      
  backend:
    build: 
      context: ./finance-wise-api
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
      - JWT_SECRET=myjwtsecret
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge